# Generated by Django 5.1.4 on 2025-02-06 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                ("id_proyecto", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                ("id_ubicacion", models.AutoField(primary_key=True, serialize=False)),
                ("direccion", models.CharField(max_length=255)),
                ("ciudad", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("codigo_postal", models.CharField(max_length=20)),
                ("pais", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                ("id_presupuesto", models.AutoField(primary_key=True, serialize=False)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "monto_utilizado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("fecha_aprobacion", models.DateField()),
                (
                    "id_proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="Gestionamiento.proyecto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                ("id_permiso", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=255)),
                ("numero_permiso", models.CharField(max_length=100, unique=True)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gestionamiento",
                        verbose_name="Foto del Robot",
                    ),
                ),
                (
                    "id_proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permisos",
                        to="Gestionamiento.proyecto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proyecto",
            name="id_ubicacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyectos",
                to="Gestionamiento.ubicacion",
            ),
        ),
    ]
